# Generated by Django 3.0.5 on 2020-04-12 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_remove_product_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favori',
            field=models.ManyToManyField(blank=True, related_name='favori', to=settings.AUTH_USER_MODEL),
        ),
    ]
